### ISSUE TITLE
simpleomr error message "WARNING:root:template contains no marks"

### ISSUE THREAD

**Issue by adelaide01** [EuracBiomedicalResearch/RescueOMR#1]
Hello, Thanks for creating RescueOMR. I am stuck halfway through the tutorial when trying to run this command:

./bin/simpleomr -d debug.png marks-it.svg test.png

The error message is:
WARNING:root:template contains no marks

But I believe I followed the instructions correctly using Inkscape. My SVG looks a lot like this https://imgur.com/a/mePbd.
I'm using a recent version of Inkscape 0.91. Only the rectangle and the object properties was used.
The tutorial has been working up until this step. Do you have any ideas?

**Comment by wavexx** [comment]
On Sun, Nov 26 2017, Adelaide Chen wrote:
> Hello, Thanks for creating RescueOMR. I am stuck halfway through the tutorial when trying to run this command:
>
> ./bin/simpleomr -d debug.png marks-it.svg test.png
>
> The error message is:
> WARNING:root:template contains no marks

Maybe you used the "label" instead of the "ID" in the object properties?
Could you attach the SVG?

**Comment by adelaide01** [comment]
Hi @wavexx,
I created a gist with the SVG code inside.
https://gist.github.com/adelaide01/7a355e3e4ad9a42a013039466d562ff8

Github doesn't support SVG attachments. The ID fields are labelled with "q1_yes, q1_no, q2_yes..."

Thanks for your help over the weekend!

**Comment by wavexx** [comment]
On Sun, Nov 26 2017, Adelaide Chen wrote:
> Hi @wavexx,
> I created a gist with the SVG code inside.
> https://gist.github.com/adelaide01/7a355e3e4ad9a42a013039466d562ff8
>
> Github doesn't support SVG attachments. The ID fields are labelled with "q1_yes, q1_no,
> q2_yes..."

The file looks correct, just produced by a differed version of inkscape
I never tested.

I updated simpleomr, which should now recognize it correctly.

**Comment by adelaide01** [comment]
Yes, it is working! Thank you so much. I will continue to finish the tutorial. It is really well done.
